name: json_dao_test
description: JSON Dao Engine testing helper
version: 0.0.1
author: null
homepage: null

publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_dao:
    path: ../json_dao/
  test: ^1.15.7
  meta: ^1.2.4

dev_dependencies:
  mockito: ^4.1.3

