name: json_dao
description: Hive implementation of JSON Dao Engine (json_dao package)
version: 0.0.1
author: null
homepage: null

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  rxdart: ^0.25.0
  uuid: ^2.2.2

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3

