name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: packages/json_dao
      steps:
        - uses: cedx/setup-dart@v2
        - uses: actions/checkout@v2
        - run: dart pub get
        - run: dart analyze
        - run: dart test
  
  hive_engine_tests:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: packages/hive_engine_json_dao
      steps:
        - uses: cedx/setup-dart@v2
        - uses: actions/checkout@v2
        - run: dart pub get
        - run: dart analyze
        - run: dart test
