name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: cedx/setup-dart@v2
        - uses: actions/checkout@v2
        - run: dart pub get
        - run: dart analyze
        - run: dart test